// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

#nullable disable

namespace WebApi.Data.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    partial class WebApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nandel.Kafka.Outbox.Data.OutboxMessage", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid")
                        .HasAnnotation("Relational:JsonPropertyName", "_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasAnnotation("Relational:JsonPropertyName", "sent_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("topic")
                        .HasAnnotation("Relational:JsonPropertyName", "topic");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Uid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SentAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("WebApi.Data.NamedCounter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ConsumedMessages")
                        .HasColumnType("integer");

                    b.Property<int>("ProducedMessages")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("named_counters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
